### ISSUE TITLE
Example usage mangles `defer` and `async` attributes

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer-build#159]
### Description
When using `polymer-build` (and by extension, the Polymer CLI) per example usage in the README, `defer` and `async` attributes are mangled so that they do not work as intended.

### Versions & Environment
- polymer-build: v0.8.4
- node: v7.7.2
- Operating System: OSX Sierra 10.12.3

#### Steps to Reproduce

1. Create an `index.html` file that loads a script (or HTML Import) with `async` or `defer` attribute
2. Transform it with `polymer-build` per the [prescribed example usage](https://github.com/Polymer/polymer-build#htmlsplitter).
3. Compare the output.

#### Expected Results
The `async` or `defer` attribute looks the same as in the input file, for example:

`<link rel="import" href="foo.html" async>`

Should look the same in the input and output `index.html`.

#### Actual Results
The `async` or `defer` attribute is given an empty string value, for example:

`<link rel="import" href="foo.html" async>`

... is mangled to ...

`<link rel="import" href="foo.html" async="">`

**Comment by FredKSchott** [comment]
Hmm, this may be an issue inside of dom5. All we do in polymer-build is update the link `href` and then re-serialize.

**Comment by FredKSchott** [comment]
Yea, looks like an issue in `parse5`: https://github.com/inikulin/parse5/issues/177 Their official stance is that all attributes should have a string value. This may just be due to an out of date understanding of the spec, I'll follow up with them to fix. Until then, a monkey-patch fix exists https://github.com/inikulin/parse5/issues/175#issuecomment-271247081 but I'd like to avoid that if we can get real support merged into parse5.

**Comment by cdata** [comment]
The only way I can declaratively lazy load my bundled resources is by manually editing the build artifacts of the Polymer CLI. Seems pretty bad.

**Comment by FredKSchott** [comment]
@cdata I'm surprised that this is causing problems though, because both `async=""` and `async` are functionally the same. [Per the spec](https://html.spec.whatwg.org/multipage/infrastructure.html#boolean-attribute):

> A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.
>
>If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

So even though the boolean attributes in your build are transformed into string attributes, the actual behavior of your built application/element shouldn't have changed. Can you share an example where this isn't working?

**Comment by FredKSchott** [comment]
Closing since I think this is a misunderstanding, feel free to comment if not and I'll reopen
