### ISSUE TITLE
compiling polymer code that's part of an angular project

### ISSUE THREAD

**Issue by jay8t6** [Polymer/polymer-build#89]
@FredKSchott this is not an issue, but I'd like to get your thoughts on writing a build process to compile polymer code written in an angular project. how would you go about using polymer-build in this scenario?

**Comment by jay8t6** [comment]
@FredKSchott Thanks! @vaadin-marcus any insight you could provide is greatly appreciated!

**Comment by vaadin-marcus** [comment]
We've been working on a general purpose Angular 2 adapter for Polymer-based web components: https://github.com/vaadin/angular2-polymer 

The workflow isn't all that smooth yet because the user still needs to use bower to download Polymer dependencies and are required to bootstrap the project differently. We also still need to figure out how to deal with AOT compilation. Please add any thoughts or requests in that repository.

**Comment by jay8t6** [comment]
Thanks @vaadin-marcus. Looks like you are working with angular 2. We are still on 1.x. Also, I do not have any custom elements in my angular project. I just need to transpile and minify my bower dependencies. Is there an easier way to do this?

**Comment by vaadin-marcus** [comment]
@jay8t6 - sounds like you probably don't need `polymer-build` in that case. You could just build a simple gulpfile that runs your code through babel and uglify.

**Comment by jay8t6** [comment]
@vaadin-marcus great, that sounds like something I wanted to hear!
